name: Bug Report
description: File a bug report to help us improve.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for helping us improve Solar-XR!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior:"
      value: |
        1. Go to '..'
        2. Click on '..'
        3. See error
  - type: dropdown
    id: prog-version
    attributes:
      label: What version of the software does the bug appear?
      options:
        - 0.1
        - 0.2
        - Release tag not listed here
        - Latest commit on main
      
        
